---
title: "DS6372-Project2"
author: "David Wei", "Anish Patel"
date: "7/23/2020"
output: html_document
---

#### Setup & General Libraries
```{r,warning=FALSE,message=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(tidyverse)

setwd("C:/Users/David/Google Drive/Code & Programming/GitHub/MSDS_6372_Applied-Statistics_Project_2/UCI_Bank_Marketing_Classification_Model/Data Files/")
df <- read.csv("bank-additional-full.csv", header=TRUE, sep=";")
head(df, 5)
```

#### Data Tidying
```{r,warning=FALSE,message=FALSE}
# renaming response variable 'y' to 'Clnt_Subcr'
df <- df %>% rename(clnt.subcr = `y`)

library(naniar)
# verifying missing data: no missing data found
vis_miss(df) + xlab("Data Columns")

# adding sequential ID column to all rows
df$ID <- seq.int(nrow(df))
df <- df %>% select(ID, everything())

# finding which columns in df are categorical
cat_class <- as.data.frame(sapply(df, class))
cat_class

# exploring the unique data values for all categorical variables
cat_types <- c(3,4,5,6,7,8,9,10,11,16,22)
for(i in cat_types){
  print(colnames(df[i]))
  print(df %>% count(df[,i]))
}

# converting all "unknown" values back to NA
df_stg <- df
df_stg[df_stg=="unknown"] <- NA
vis_miss(df_stg, warn_large_data = FALSE) + xlab("Data Columns")

# filtering out all NA values from dataset
df_stg <- df_stg %>% filter(!is.na(job) & !is.na(marital) & !is.na(education) & !is.na(default)
                                      & !is.na(housing) & !is.na(loan) & !is.na(contact))
# checking all missing variables filtered out
vis_miss(df_stg) + xlab("Data Columns")
# validating reduction in row totals after filtering missing data
nrow(df)
nrow(df_stg) 

# # Converting all int to numeric value types
# int_types <- c(1,11,12,13,14)
# for(i in int_types){
#   df_stg[,i] <- as.numeric(df_stg[, i])
# }

# new df storing ID and all converted categorical variables into factor types
df_cat <- df_stg
for(i in cat_types){
  df_cat[, i] <- factor(df_cat[,i])
  x <- paste(colnames(df_cat[i]),"desc", sep="_")
  colnames(df_cat)[i] <- paste(x)
}

# create new df containing ID and all converted categorical variables into numerical types
df_cat_num <- df_stg
for(i in cat_types){
  df_cat_num[, i] <- as.numeric(factor(df_cat_num[,i]))
  x <- paste(colnames(df_cat_num[i]),"ID", sep="_")
  colnames(df_cat_num)[i] <- paste(x)
}

# new df storing all factored categorical values including the ID
cat_columns <- c(1,3,4,5,6,7,8,9,10,11,16,22)
# 2 dfs, 1 storing all the IDs (df_cat_num_short), the other storying all the factored "descriptions" (df_cat_short)
df_cat_num_short <- data.frame(df_cat_num[, cat_columns])
df_cat_short <- data.frame(df_cat[, cat_columns])

# storying all numerical data into temp df excluding categorical types
df_num_only <- df[, -cat_types]

# joining the categorical factors (desc) with it's numerical types (IDs) then re-ordering
df_cat_merge <- merge(x=df_cat_num_short, y=df_cat_short, by="ID", all.x=TRUE)
df_cat_merge <- df_cat_merge[c(1,2,13,3,14,4,15,5,16,6,17,7,18,8,19,9,20,10,21,11,22,12,23)]

# joining all numerical with categorical data together as final df
df_final <- merge(x=df_cat_merge, y=df_num_only, by="ID", all.x=TRUE)
head(df_final, 1)
View(df_final)
# validating df matches all prior df stages
nrow(df) #raw
nrow(df_stg) #filterd NA
nrow(df_final) #organized
table(df_stg$clnt.subcr)

```

## EDA
```{r,warning=FALSE,message=FALSE}
library(GGally)
#summary of all numerical variables
summary(df_num_only)

num_types <- c(1,11,12,13,14,16,17,18,19,20)
ggpairs(bank_df_num, columns=num_types, aes(colour=clnt.subcr))

# is there a relationship between # of contacts made and the month or week?
library(stringr)
df_final$month_cap <- str_to_title(df_final$month_desc)
df_final$month_cap <- factor(df_final$month_cap, levels=month.abb)
# number of campaigns run per month
df_final %>% ggplot(aes(x=month_cap, y=campaign,fill=day_of_week_desc)) + geom_bar(stat="identity") + scale_x_discrete(limits=month.abb) + labs(title="# of Campaigns per Month by Day", x="Month", y="# of Campaigns", fill="Day of Week")

```












